wgx: Taskbar Icon Overlays
Taskbar Icon Overlays
Functions
BOOL WgxSetTaskbarIconOverlay (HWND hWindow, HINSTANCE hInstance, int resource_id, wchar_t *description)
Sets an overlay icon for the application's taskbar icon.
BOOL WgxRemoveTaskbarIconOverlay (HWND hWindow)
Removes an overlay icon from the application's taskbar icon.
Detailed Description
Function Documentation
BOOL WgxSetTaskbarIconOverlay (HWND hWindow, HINSTANCE hInstance, int resource_id, wchar_t * description)
Sets an overlay icon for the application's taskbar icon.
Parameters
[in] hWindow handle to the main application's window.
[in] hInstance handle to an instance of the module containing the icon resource.
[in] resource_id the identifier of the overlay icon resource. Identifier equal to -1 causes icon removal.
[in] description the description for the overlay icon, needed for accessibility.
Returns
Boolean value. TRUE indicates success.
Note
Taskbar icon overlays are supported by Windows 7 and more recent Windows editions. On older Windows editions this routine does nothing.
Definition at line 70 of file taskbar.c.
References WgxDbgPrint(), and WgxLoadIcon().
Referenced by WgxRemoveTaskbarIconOverlay().
BOOL WgxRemoveTaskbarIconOverlay (HWND hWindow)
Removes an overlay icon from the application's taskbar icon.
Parameters
[in] hWindow handle to the main application's window.
Returns
Boolean value. TRUE indicates success.
Note
Taskbar icon overlays are supported by Windows 7 and more recent Windows editions. On older Windows editions this routine does nothing.
Definition at line 122 of file taskbar.c.
References WgxSetTaskbarIconOverlay().