wgx: Internationalization
Internationalization
Functions
BOOL WgxBuildResourceTable (PWGX_I18N_RESOURCE_ENTRY table, char *path)
Extracts localization strings from a file to a table.
void WgxApplyResourceTable (PWGX_I18N_RESOURCE_ENTRY table, HWND hWindow)
Applies an i18n table to the dialog window.
void WgxSetText (HWND hWnd, PWGX_I18N_RESOURCE_ENTRY table, char *key)
Applies an i18n table to individual GUI control.
wchar_t * WgxGetResourceString (PWGX_I18N_RESOURCE_ENTRY table, char *key)
Retrieves a localization string.
void WgxDestroyResourceTable (PWGX_I18N_RESOURCE_ENTRY table)
Destroys an i18n table.
Detailed Description
Function Documentation
BOOL WgxBuildResourceTable (PWGX_I18N_RESOURCE_ENTRY table, char * path)
Extracts localization strings from a file to a table.
Parameters
[in,out] table pointer to the table.
[in] path path of the file.
Returns
Boolean value. TRUE indicates success.
Note
Path must use double back slashes instead of single ones.
Definition at line 69 of file i18n.c.
References WgxDbgPrint(), and WgxDbgPrintLastError().
void WgxApplyResourceTable (PWGX_I18N_RESOURCE_ENTRY table, HWND hWindow)
Applies an i18n table to the dialog window.
Parameters
[in] table pointer to the i18n table.
[in] hWindow handle to the window.
Definition at line 172 of file i18n.c.
References WgxDbgPrint(), and WgxDbgPrintLastError().
wchar_t* WgxGetResourceString (PWGX_I18N_RESOURCE_ENTRY table, char * key)
Retrieves a localization string.
Parameters
[in] table pointer to the i18n table.
[in] key pointer to the key string.
Returns
A pointer to the localized string if available or to the default string otherwise.
Note
The returned string should be freed by a call to the free() routine after a use.
Definition at line 231 of file i18n.c.
References WgxDbgPrint(), and WgxDbgPrintLastError().
Referenced by WgxSetText().
void WgxDestroyResourceTable (PWGX_I18N_RESOURCE_ENTRY table)
Destroys an i18n table.
Parameters
[in] table pointer to the i18n table.
Definition at line 277 of file i18n.c.
References WgxDbgPrintLastError().