zenwinx: Keyboard
Keyboard
Functions
void kb_close (void)
Closes all opened keyboards.
char * winx_get_error_description (unsigned long status)
Retrieves a human readable explanation of the NT status code.
int winx_kb_init (void)
Prepares all existing keyboards for work with user input related procedures.
int kb_read (PKEYBOARD_INPUT_DATA pKID, int msec_timeout)
Checks the console for keyboard input.
Detailed Description
Function Documentation
void kb_close (void)
Closes all opened keyboards.
Definition at line 254 of file keyboard.c.
References winx_destroy_event(), winx_printf(), and winx_sleep().
Referenced by winx_exit(), winx_reboot(), and winx_shutdown().
char* winx_get_error_description (unsigned long status)
Retrieves a human readable explanation of the NT status code.
Parameters
[in] status the NT status code.
Returns
A pointer to string containing the status explanation.
Note
This function returns explanations only for well known codes. Otherwise it returns an empty string.
Example:
printf("%s\n",winx_get_error_description(STATUS_ACCESS_VIOLATION));
// prints "access violation"
Definition at line 525 of file dbg.c.
int winx_kb_init (void)
Prepares all existing keyboards for work with user input related procedures.
If checking of first keyboard fails it waits ten seconds for the initialization. This is needed for wireless devices.
Returns
Zero for success, negative value otherwise.
Definition at line 185 of file keyboard.c.
References winx_create_event(), winx_create_thread(), winx_printf(), and winx_sleep().
int kb_read (PKEYBOARD_INPUT_DATA pKID, int msec_timeout)
Checks the console for keyboard input.
Tries to read from all keyboard devices until specified time-out expires.
Parameters
[out] pKID pointer to the structure receiving keyboard input.
[in] msec_timeout time-out interval in milliseconds.
Returns
Zero if some key was pressed, negative value otherwise.
Definition at line 296 of file keyboard.c.
References winx_get_error_description(), winx_printf(), winx_sleep(), and winx_xtime().
Referenced by winx_breakhit(), winx_kb_read(), and winx_prompt_ex().