zenwinx: Console
Console
Functions
int kb_read (PKEYBOARD_INPUT_DATA pKID, int msec_timeout)
Checks the console for keyboard input.
void winx_print (char *string)
Displays ANSI string on the screen.
int winx_putch (int ch)
putch() native equivalent.
int winx_puts (const char *string)
puts() native equivalent.
int winx_printf (const char *format,...)
printf() native equivalent.
int winx_kbhit (int msec)
Checks the console for keyboard input.
int winx_kb_read (KBD_RECORD *kbd_rec, int msec)
Low level winx_kbhit() equivalent.
int winx_breakhit (int msec)
Checks the console for the 'Break' character on the keyboard input.
int winx_getch (void)
getch() native equivalent.
int winx_getche (void)
getche() native equivalent.
int winx_gets (char *string, int n)
gets() native equivalent with limited number of characters to read.
void winx_init_history (winx_history *h)
Initializes commands history.
void winx_destroy_history (winx_history *h)
Destroys commands history.
int winx_prompt_ex (char *prompt, char *string, int n, winx_history *h)
Displays prompt on the screen and waits for the user input. When user hits the return key it fills the string pointed by the second parameter by characters read.
int winx_prompt (char *prompt, char *string, int n)
Simplified analog of winx_prompt_ex() call. Has no support of commands history.
int winx_print_array_of_strings (char **strings, int line_width, int max_rows, char *prompt, int divide_to_pages)
Displays text on the screen, divided to pages if requested so. Accepts array of strings as an input.
Detailed Description
Function Documentation
int kb_read (PKEYBOARD_INPUT_DATA pKID, int msec_timeout)
Checks the console for keyboard input.
Tries to read from all keyboard devices until specified time-out expires.
Parameters
[out] pKID pointer to the structure receiving keyboard input.
[in] msec_timeout time-out interval in milliseconds.
Returns
Zero if some key was pressed, negative value otherwise.
Definition at line 296 of file keyboard.c.
References winx_get_error_description(), winx_printf(), winx_sleep(), and winx_xtime().
Referenced by winx_breakhit(), winx_kb_read(), and winx_prompt_ex().
void winx_print (char * string)
Displays ANSI string on the screen.
This routine requires no library initialization, therefore may be used when it fails.
Parameters
[in] string the string to be displayed.
Note
Does not recognize \b character.
Definition at line 42 of file stdio.c.
References winx_putch().
Referenced by winx_create_global_heap(), winx_enable_dbg_log(), and winx_printf().
int winx_putch (int ch)
putch() native equivalent.
Note
Does not recognize \b character.
Definition at line 75 of file stdio.c.
Referenced by winx_getche(), winx_print(), and winx_prompt_ex().
int winx_puts (const char * string)
puts() native equivalent.
Note
Does not recognize \b character.
Definition at line 103 of file stdio.c.
References winx_printf().
int winx_printf (const char * format, ...)
printf() native equivalent.
Note
Does not recognize \b character.
Definition at line 113 of file stdio.c.
References winx_heap_free(), winx_print(), and winx_vsprintf().
Referenced by kb_close(), kb_read(), MarkWindowsBootAsSuccessful(), winx_enable_dbg_log(), winx_get_file_contents(), winx_get_windows_boot_options(), winx_kb_init(), winx_print_array_of_strings(), winx_prompt_ex(), and winx_puts().
int winx_kbhit (int msec)
Checks the console for keyboard input.
Waits for an input during the specified time interval.
Parameters
[in] msec the time interval, in milliseconds.
Returns
If any key was pressed, the return value is the ascii character or zero for the control keys. Negative value indicates failure.
Note
If an INFINITE time constant is passed, the time-out interval never elapses.
Definition at line 143 of file stdio.c.
References winx_kb_read().
int winx_kb_read (KBD_RECORD * kbd_rec, int msec)
Low level winx_kbhit() equivalent.
Parameters
[in] kbd_rec pointer to structure receiving key information.
[in] msec the timeout interval, in milliseconds.
Returns
If any key was pressed, the return value is the ascii character or zero for the control keys. Negative value indicates failure.
Note
If an INFINITE time constant is passed, the time-out interval never elapses.
Definition at line 160 of file stdio.c.
References kb_read().
Referenced by winx_getch(), and winx_kbhit().
int winx_breakhit (int msec)
Checks the console for the 'Break' character on the keyboard input.
Waits for an input during the specified time interval.
Parameters
[in] msec the time interval, in milliseconds.
Returns
If the 'Break' key was pressed, the return value is zero. Otherwise it returns negative value.
Note
If an INFINITE time constant is passed, the time-out interval never elapses.
Definition at line 183 of file stdio.c.
References kb_read().
int winx_getche (void)
getche() native equivalent.
Note
Does not recognize \b character.
Does not recognize tabulation.
Definition at line 213 of file stdio.c.
References winx_getch(), and winx_putch().
int winx_gets (char * string, int n)
gets() native equivalent with limited number of characters to read.
Parameters
[out] string the storage for the input string.
[in] n the maximum number of characters to read.
Returns
Number of characters read including terminal zero. Negative value indicates failure.
Note
Does not recognize tabulation.
Definition at line 232 of file stdio.c.
References winx_prompt_ex().
void winx_init_history (winx_history * h)
Initializes commands history.
Parameters
[in] h pointer to structure holding the commands history.
Definition at line 242 of file stdio.c.
void winx_destroy_history (winx_history * h)
Destroys commands history.
Parameters
[in] h pointer to structure holding the commands history.
Note
There is no need to call winx_init_history() after this call to reinitialize the structure.
Definition at line 259 of file stdio.c.
References winx_heap_free(), and winx_list_destroy().
int winx_prompt_ex (char * prompt, char * string, int n, winx_history * h)
Displays prompt on the screen and waits for the user input. When user hits the return key it fills the string pointed by the second parameter by characters read.
Parameters
[in] prompt the string to be printed as prompt.
[out] string the storage for the input string.
[in] n the size of the string, in characters.
[in,out] h pointer to structure holding the commands history. May be NULL.
Returns
Number of characters read including terminal zero. Negative value indicates failure.
Note
Recognizes properly both backslash and escape keys.
The sentence above works fine only when user input stands in a single line of the screen.
Recognizes arrow keys to walk through commands history.
Does not recognize tabulation.
Definition at line 328 of file stdio.c.
References kb_read(), winx_heap_free(), winx_printf(), and winx_putch().
Referenced by winx_gets(), and winx_prompt().
int winx_prompt (char * prompt, char * string, int n)
Simplified analog of winx_prompt_ex() call. Has no support of commands history.
Note
Does not recognize tabulation.
Definition at line 486 of file stdio.c.
References winx_prompt_ex().
int winx_print_array_of_strings (char ** strings, int line_width, int max_rows, char * prompt, int divide_to_pages)
Displays text on the screen, divided to pages if requested so. Accepts array of strings as an input.
Parameters
[in] strings - array of strings to be displayed. Last entry of it must be NULL to indicate the end of array.
[in] line_width - maximum line width, in characters.
[in] max_rows - maximum number of lines on the screen.
[in] prompt - the string to be displayed as a prompt to hit any key to list forward.
[in] divide_to_pages - boolean value indicating whether the text must be divided to pages or not. If this parameter is zero, all others, except of the first one, will be ignored.
Note
If user hits Escape or Pause at the prompt, text listing breaks immediately.
Returns
Zero for success, negative value otherwise.
Note
Does not recognize \b character.
Definition at line 552 of file stdio.c.
References winx_heap_free(), and winx_printf().