zenwinx: Debug
Debug
Typedefs
typedef struct _winx_dbg_log_entry winx_dbg_log_entry
Describes a log list entry.
typedef struct
_DBG_OUTPUT_DEBUG_STRING_BUFFER DBG_OUTPUT_DEBUG_STRING_BUFFER
Internal structure used to deliver information to the Debug View program.
Enumerations
enum
Functions
int winx_dbg_init (void)
Initializes the debugging facility.
void winx_dbg_close (void)
Deinitializes the debugging facility.
void winx_dbg_print (char *format,...)
Delivers a message to the Debug View program and appends it to the log file as well.
void winx_dbg_print_ex (unsigned long status, char *format,...)
Delivers a message to the Debug View program and appends it to the log file as well.
void winx_dbg_print_header (char ch, int width, char *format,...)
Delivers a message to the Debug View program and appends it to the log file as well.
char * winx_get_error_description (unsigned long status)
Retrieves a human readable explanation of the NT status code.
void winx_flush_dbg_log (void)
Appends all collected debugging information to the log file.
void winx_enable_dbg_log (char *path)
Enables debug logging to the file.
void winx_disable_dbg_log (void)
Disables debug logging to the file.
Detailed Description
Typedef Documentation
typedef struct _winx_dbg_log_entry winx_dbg_log_entry
Describes a log list entry.
typedef struct _DBG_OUTPUT_DEBUG_STRING_BUFFER DBG_OUTPUT_DEBUG_STRING_BUFFER
Internal structure used to deliver information to the Debug View program.
Enumeration Type Documentation
anonymous enum
Definition at line 220 of file dbg.c.
Function Documentation
int winx_dbg_init (void)
Initializes the debugging facility.
Returns
Zero for success, negative value otherwise.
Definition at line 65 of file dbg.c.
References winx_init_spin_lock().
Referenced by winx_init_library().
void winx_dbg_close (void)
Deinitializes the debugging facility.
Definition at line 79 of file dbg.c.
References winx_destroy_spin_lock().
Referenced by winx_unload_library().
void winx_dbg_print (char * format, ...)
Delivers a message to the Debug View program and appends it to the log file as well.
Note
If : $LE appears at end of the format string, the last error code will be appended to the message as well as its description.
If : $NS appears at end of the format string, the NT status code of the last operation will be appended to the message as well as its description.
Not all system API set last status code. Use winx_dbg_print_ex to catch the status for sure.
Definition at line 276 of file dbg.c.
References winx_heap_free(), winx_sprintf(), winx_to_utf8(), and winx_vsprintf().
Referenced by winx_dbg_print_ex(), and winx_dbg_print_header().
void winx_dbg_print_ex (unsigned long status, char * format, ...)
Delivers a message to the Debug View program and appends it to the log file as well.
Appends specified status code to the message as well as its description.
Parameters
[in] status the NT status code.
[in] format the format string.
[in] ... the parameters.
Example:
NTSTATUS Status = NtCreateFile(...);
if(!NT_SUCCESS(Status)){
    winx_dbg_print_ex(Status,"Cannot create %s file",filename);
}
Definition at line 388 of file dbg.c.
References winx_dbg_print(), winx_heap_free(), and winx_vsprintf().
void winx_dbg_print_header (char ch, int width, char * format, ...)
Delivers a message to the Debug View program and appends it to the log file as well.
Decorates the message by specified character at both sides.
Parameters
[in] ch the character to be used for decoration. If zero value is passed, DEFAULT_DBG_PRINT_DECORATION_CHAR is used.
[in] width the width of the resulting message, in characters. If zero value is passed, DEFAULT_DBG_PRINT_HEADER_WIDTH is used.
[in] format the format string.
[in] ... the parameters.
Definition at line 417 of file dbg.c.
References winx_dbg_print(), winx_heap_free(), and winx_vsprintf().
Referenced by winx_scan_disk().
char* winx_get_error_description (unsigned long status)
Retrieves a human readable explanation of the NT status code.
Parameters
[in] status the NT status code.
Returns
A pointer to string containing the status explanation.
Note
This function returns explanations only for well known codes. Otherwise it returns an empty string.
Example:
printf("%s\n",winx_get_error_description(STATUS_ACCESS_VIOLATION));
// prints "access violation"
Definition at line 525 of file dbg.c.
Referenced by kb_read().
void winx_enable_dbg_log (char * path)
Enables debug logging to the file.
Parameters
[in] path the path to the logfile. NULL or an empty string forces to flush all collected data to the disk and disable logging to the file.
Definition at line 665 of file dbg.c.
References winx_acquire_spin_lock(), winx_heap_free(), winx_print(), winx_printf(), winx_release_spin_lock(), and winx_strdup().
Referenced by winx_disable_dbg_log().