zenwinx: Lists
Lists
Functions
list_entry * winx_list_insert_item (list_entry **phead, list_entry *prev, long size)
Inserts an item to double linked list.
void winx_list_remove_item (list_entry **phead, list_entry *item)
Removes an item from double linked list.
void winx_list_destroy (list_entry **phead)
Destroys a double linked list.
Detailed Description
Function Documentation
list_entry* winx_list_insert_item (list_entry ** phead, list_entry * prev, long size)
Inserts an item to double linked list.
Allocates memory for an item to be inserted.
Parameters
[in,out] phead pointer to a variable pointing to the list head.
[in] prev pointer to an item preceeding to the new item. If this parameter is NULL, the new head will be inserted.
[in] size the size of an item to be inserted, in bytes.
Returns
Pointer to the inserted list item. NULL indicates failure.
Definition at line 38 of file list.c.
Referenced by winx_add_volume_region(), winx_ftw_dump_file(), and winx_get_free_volume_regions().
void winx_list_remove_item (list_entry ** phead, list_entry * item)
Removes an item from double linked list.
Frees memory allocated for an item to be removed.
Parameters
[in,out] phead pointer to a variable pointing to the list head.
[in] item pointer to an item which must be removed.
Definition at line 80 of file list.c.
References winx_heap_free().
Referenced by winx_add_volume_region(), and winx_sub_volume_region().
void winx_list_destroy (list_entry ** phead)
Destroys a double linked list.
Frees memory allocated for all list items.
Parameters
[in,out] phead pointer to a variable pointing to the list head.
Definition at line 115 of file list.c.
References winx_heap_free().
Referenced by validate_blockmap(), winx_destroy_history(), winx_ftw_dump_file(), winx_ftw_release(), winx_get_free_volume_regions(), and winx_release_free_volume_regions().