zenwinx: File
File
Functions
WINX_FILE * winx_fopen (const char *filename, const char *mode)
fopen() native equivalent.
WINX_FILE * winx_fbopen (const char *filename, const char *mode, int buffer_size)
winx_fopen analog, but allocates a buffer to speedup sequential write requests.
size_t winx_fread (void *buffer, size_t size, size_t count, WINX_FILE *f)
fread() native equivalent.
size_t winx_fwrite (const void *buffer, size_t size, size_t count, WINX_FILE *f)
fwrite() native equivalent.
int winx_ioctl (WINX_FILE *f, int code, char *description, void *in_buffer, int in_size, void *out_buffer, int out_size, int *pbytes_returned)
Sends an I/O control code to the specified device.
int winx_fflush (WINX_FILE *f)
fflush() native equivalent.
ULONGLONG winx_fsize (WINX_FILE *f)
Retrieves the size of the file.
void winx_fclose (WINX_FILE *f)
fclose() native equivalent.
int winx_create_directory (const char *path)
Creates a directory.
int winx_delete_file (const char *filename)
Deletes a file.
void * winx_get_file_contents (const char *filename, size_t *bytes_read)
Reads file entirely and returns pointer to data read.
void winx_release_file_contents (void *contents)
Releases memory allocated by winx_get_file_contents().
NTSTATUS winx_defrag_fopen (winx_file_info *f, int action, HANDLE *phandle)
Opens the file for defragmentation related actions.
void winx_defrag_fclose (HANDLE h)
Closes a file opened by winx_defrag_fopen.
winx_file_info * ntfs_scan_disk (char volume_letter, int flags, ftw_filter_callback fcb, ftw_progress_callback pcb, ftw_terminator t, void *user_defined_data)
winx_scan_disk analog, but optimized for fastest NTFS scan.
void validate_blockmap (winx_file_info *f)
Validates map of file blocks, destroys it in case of errors found.
int winx_ftw_dump_file (winx_file_info *f, ftw_terminator t, void *user_defined_data)
Retrieves information about the file disposition.
winx_file_info * winx_ftw (short *path, int flags, ftw_filter_callback fcb, ftw_progress_callback pcb, ftw_terminator t, void *user_defined_data)
Returns list of files contained in directory, and all its subdirectories if WINX_FTW_RECURSIVE flag is passed.
winx_file_info * winx_scan_disk (char volume_letter, int flags, ftw_filter_callback fcb, ftw_progress_callback pcb, ftw_terminator t, void *user_defined_data)
winx_ftw analog, but optimized for the entire disk scan.
void winx_ftw_release (winx_file_info *filelist)
Releases resources allocated by winx_ftw or winx_scan_disk.
Variables
struct names_pair special_file_names []
Auxiliary table helping to replace file name by name accepted by Windows in case of special NTFS files.
Detailed Description
Function Documentation
WINX_FILE* winx_fopen (const char * filename, const char * mode)
fopen() native equivalent.
Note
Only r, w, a, r+, w+, a+ modes are supported.
Definition at line 33 of file file.c.
Referenced by MarkWindowsBootAsSuccessful(), winx_fbopen(), winx_get_file_contents(), winx_vflush(), and winx_vopen().
WINX_FILE* winx_fbopen (const char * filename, const char * mode, int buffer_size)
winx_fopen analog, but allocates a buffer to speedup sequential write requests.
The last parameter specifies the buffer size, in bytes. Returns NULL if buffer allocation failed.
Definition at line 116 of file file.c.
References winx_fclose(), and winx_fopen().
int winx_ioctl (WINX_FILE * f, int code, char * description, void * in_buffer, int in_size, void * out_buffer, int out_size, int * pbytes_returned)
Sends an I/O control code to the specified device.
Parameters
[in] f the file handle.
[in] code the IOCTL code.
[in] description the string explaining the meaning of the request, used by error handling code.
[in] in_buffer the input buffer pointer.
[in] in_size the input buffer size, in bytes.
[out] out_buffer the output buffer pointer.
[in] out_size the output buffer size, in bytes.
[out] pbytes_returned pointer to the variable receiving the number of bytes written to the output buffer.
Returns
Zero for success, negative value otherwise.
Definition at line 279 of file file.c.
int winx_fflush (WINX_FILE * f)
fflush() native equivalent.
Returns
Zero for success, negative value otherwise.
Definition at line 320 of file file.c.
Referenced by winx_vflush().
ULONGLONG winx_fsize (WINX_FILE * f)
Retrieves the size of the file.
Parameters
[in] f pointer to structure returned by winx_fopen() call.
Returns
The size of the file, in bytes.
Definition at line 341 of file file.c.
Referenced by winx_get_file_contents().
int winx_create_directory (const char * path)
Creates a directory.
Parameters
[in] path the native path to the directory.
Returns
Zero for success, negative value otherwise.
Note
If the requested directory already exists this function completes successfully.
Definition at line 386 of file file.c.
Referenced by winx_create_path().
int winx_delete_file (const char * filename)
Deletes a file.
Parameters
[in] filename the native path to the file.
Returns
Zero for success, negative value otherwise.
Definition at line 432 of file file.c.
void* winx_get_file_contents (const char * filename, size_t * bytes_read)
Reads file entirely and returns pointer to data read.
Parameters
[in] filename the native path to the file.
[out] bytes_read number of bytes read.
Returns
Pointer to data, NULL indicates failure.
Note
Returned buffer is two bytes larger than the file contents. This allows to add terminal zero easily.
Definition at line 467 of file file.c.
References winx_fclose(), winx_fopen(), winx_fread(), winx_fsize(), winx_heap_free(), and winx_printf().
NTSTATUS winx_defrag_fopen (winx_file_info * f, int action, HANDLE * phandle)
Opens the file for defragmentation related actions.
Parameters
[in] f pointer to structure containing the file information.
[in] action one of the WINX_OPEN_XXX constants indicating an action file needs to be opened for:
WINX_OPEN_FOR_DUMP - open for FSCTL_GET_RETRIEVAL_POINTERS
WINX_OPEN_FOR_BASIC_INFO - open for NtQueryInformationFile(FILE_BASIC_INFORMATION)
WINX_OPEN_FOR_MOVE - open for FSCTL_MOVE_FILE
[out] phandle pointer to variable receiving file handle.
Returns
NTSTATUS code.
Definition at line 568 of file file.c.
References winx_get_os_version(), and winx_wcsistr().
Referenced by winx_ftw_dump_file().
winx_file_info * ntfs_scan_disk (char volume_letter, int flags, ftw_filter_callback fcb, ftw_progress_callback pcb, ftw_terminator t, void * user_defined_data)
winx_scan_disk analog, but optimized for fastest NTFS scan.
Note
When stop request is sent by the caller, file paths cannot be built, because of missing information about directories not scanned yet.
Definition at line 1791 of file ftw_ntfs.c.
References winx_ftw_release().
Referenced by winx_scan_disk().
void validate_blockmap (winx_file_info * f)
Validates map of file blocks, destroys it in case of errors found.
Definition at line 76 of file ftw.c.
References winx_list_destroy().
Referenced by winx_ftw_dump_file().
int winx_ftw_dump_file (winx_file_info * f, ftw_terminator t, void * user_defined_data)
Retrieves information about the file disposition.
Parameters
[out] f pointer to structure receiving the information.
[in] t address of procedure to be called each time when winx_ftw_dump_file would like to know whether it must be terminated or not. Nonzero value, returned by terminator, forces file dump to be terminated.
[in] user_defined_data pointer to data passed to the registered terminator.
Returns
Zero for success, negative value otherwise.
Note
Callback procedure should complete as quickly as possible to avoid slowdown of the scan.
For resident NTFS streams (small files and directories located inside MFT) this function resets all the file disposition structure fields to zero.
Definition at line 132 of file ftw.c.
References validate_blockmap(), winx_defrag_fclose(), winx_defrag_fopen(), winx_heap_free(), winx_list_destroy(), and winx_list_insert_item().
winx_file_info* winx_ftw (short * path, int flags, ftw_filter_callback fcb, ftw_progress_callback pcb, ftw_terminator t, void * user_defined_data)
Returns list of files contained in directory, and all its subdirectories if WINX_FTW_RECURSIVE flag is passed.
Parameters
[in] path the native path of the directory to be scanned.
[in] flags combination of WINX_FTW_xxx flags, defined in zenwinx.h
[in] fcb address of callback routine to be called for each file; if it returns nonzero value, all file's children will be skipped. Zero value forces to continue subdirectory scan. Note that the filter callback is called when the complete information is gathered for the file.
[in] pcb address of callback routine to be called for each file to update progress information specific for the caller. Note that the progress callback may be called when all the file information is gathered except of the file name and path. If WINX_FTW_SKIP_RESIDENT_STREAMS flag is set, the progress callback will never be called for files of zero length and resident NTFS streams.
[in] t address of procedure to be called each time when winx_ftw would like to know whether it must be terminated or not. Nonzero value, returned by terminator, forces file tree walk to be terminated.
[in] user_defined_data pointer to data passed to all registered callbacks.
Returns
List of files, NULL indicates failure.
Note
Optimized for little directories scan.
To scan root directory, add trailing backslash to the path.
fcb parameter may be equal to NULL if no filtering is needed.
pcb parameter may be equal to NULL.
Callback procedures should complete as quickly as possible to avoid slowdown of the scan.
Does not recognize additional NTFS data streams.
For resident NTFS streams (small files and directories located inside MFT) this function resets all the file disposition structure fields to zero.
WINX_FTW_DUMP_FILES flag must be set to accept WINX_FTW_SKIP_RESIDENT_STREAMS.
Files with empty paths become excluded from the list, but may pass through the filter callback.
Example:
int filter(winx_file_info *f, void *user_defined_data)
{
    if(skip_directory(f))
        return 1;    // skip contents of the current directory
    return 0; // continue walk
}
void update_progress(winx_file_info *f, void *user_defined_data)
{
    if(is_directory(f))
        dir_count ++;
    // etc.
}
int terminator(void *user_defined_data)
{
    if(stop_event)
        return 1; // terminate walk
    return 0;     // continue walk
}
// list all files on disk c:
filelist = winx_ftw(L"\\??\\c:\\",0,filter,update_progress,
    terminator,&user_defined_data);
// ...
// process list of files
// ...
winx_ftw_release(filelist);
Definition at line 772 of file ftw.c.
References winx_ftw_release().
winx_file_info* winx_scan_disk (char volume_letter, int flags, ftw_filter_callback fcb, ftw_progress_callback pcb, ftw_terminator t, void * user_defined_data)
winx_ftw analog, but optimized for the entire disk scan.
Note
NTFS is scanned directly through reading MFT records, because this highly (25 times) speeds up the scan. For FAT we have noticed no speedup (even slowdown) while trying to walk trough FAT entries. This is because Windows file cache makes access even faster. UDF has been never tested in direct mode because of its highly complicated standard.
Definition at line 815 of file ftw.c.
References ntfs_scan_disk(), winx_dbg_print_header(), winx_ftw_release(), winx_get_volume_information(), winx_toupper(), and winx_xtime().
void winx_ftw_release (winx_file_info * filelist)
Releases resources allocated by winx_ftw or winx_scan_disk.
Parameters
[in] filelist pointer to list of files.
Definition at line 885 of file ftw.c.
References winx_heap_free(), and winx_list_destroy().
Referenced by ntfs_scan_disk(), winx_ftw(), and winx_scan_disk().
Variable Documentation
struct names_pair special_file_names[]
Initial value:
= {
    { L"$Secure:$SDH",                  L"$Secure:$SDH:$INDEX_ALLOCATION" },
    { L"$Secure:$SII",                  L"$Secure:$SII:$INDEX_ALLOCATION" },
    { L"$Extend",                       L"$Extend:$I30:$INDEX_ALLOCATION" },
    { L"$Extend\\$Quota:$Q",            L"$Extend\\$Quota:$Q:$INDEX_ALLOCATION" },
    { L"$Extend\\$Quota:$O",            L"$Extend\\$Quota:$O:$INDEX_ALLOCATION" },
    { L"$Extend\\$ObjId:$O",            L"$Extend\\$ObjId:$O:$INDEX_ALLOCATION" },
    { L"$Extend\\$Reparse:$R",          L"$Extend\\$Reparse:$R:$INDEX_ALLOCATION" },
    { L"$Extend\\$RmMetadata",          L"$Extend\\$RmMetadata:$I30:$INDEX_ALLOCATION" },
    { L"$Extend\\$RmMetadata\\$Txf",    L"$Extend\\$RmMetadata\\$Txf:$I30:$INDEX_ALLOCATION" },
    { L"$Extend\\$RmMetadata\\$TxfLog", L"$Extend\\$RmMetadata\\$TxfLog:$I30:$INDEX_ALLOCATION" },
    { NULL, NULL }
}
Auxiliary table helping to replace file name by name accepted by Windows in case of special NTFS files.
Definition at line 543 of file file.c.