zenwinx: String
String
Functions
void winx_init_case_tables (void)
Initializes tables for the character case conversion.
char winx_toupper (char c)
Reliable _toupper analog.
char winx_tolower (char c)
Reliable _tolower analog.
wchar_t winx_towupper (wchar_t c)
Reliable towupper analog.
wchar_t winx_towlower (wchar_t c)
Reliable towlower analog.
wchar_t * winx_wcsupr (wchar_t *s)
Reliable _wcsupr analog.
wchar_t * winx_wcslwr (wchar_t *s)
Reliable _wcslwr analog.
char * winx_strdup (const char *s)
strdup equivalent.
wchar_t * winx_wcsdup (const wchar_t *s)
wcsdup equivalent.
int winx_wcsicmp (const wchar_t *s1, const wchar_t *s2)
Case insensitive version of wcscmp.
wchar_t * winx_wcsistr (const wchar_t *s1, const wchar_t *s2)
Case insensitive version of wcsstr.
char * winx_stristr (const char *s1, const char *s2)
Case insensitive version of strstr.
int winx_wcsmatch (wchar_t *string, wchar_t *mask, int flags)
Compares a string with a mask.
char * winx_vsprintf (const char *format, va_list arg)
Robust and flexible alternative to _vsnprintf.
char * winx_sprintf (const char *format,...)
Robust and flexible alternative to _snprintf.
int winx_patcomp (winx_patlist *patterns, wchar_t *string, wchar_t *delim, int flags)
Compiles string of patterns to internal representation.
int winx_patfind (wchar_t *string, winx_patlist *patterns)
Searches for patterns in a string.
int winx_patcmp (wchar_t *string, winx_patlist *patterns)
Compares a string with patterns.
void winx_patfree (winx_patlist *patterns)
Frees resources allocated by winx_patcomp.
int winx_bytes_to_hr (ULONGLONG bytes, int digits, char *buffer, int length)
Converts number of bytes to a human readable string.
ULONGLONG winx_hr_to_bytes (char *string)
Converts human readable string to number of bytes.
void winx_to_utf8 (char *dst, int size, wchar_t *src)
Converts a string to UTF-8 encoding.
Detailed Description
Function Documentation
void winx_init_case_tables (void)
Initializes tables for the character case conversion.
Definition at line 50 of file string.c.
Referenced by winx_init_library().
char winx_toupper (char c)
Reliable _toupper analog.
MSDN states: "In order for toupper to give the expected results, __isascii and islower must both return nonzero". winx_toupper has no such limitation.
Note
Converts ASCII characters only (as well as _toupper function included in ntdll library).
Definition at line 68 of file string.c.
Referenced by winx_get_drive_type(), winx_get_free_volume_regions(), winx_get_volume_information(), winx_scan_disk(), winx_str2time(), winx_vflush(), and winx_vopen().
char winx_tolower (char c)
Reliable _tolower analog.
MSDN states: "In order for tolower to give the expected results, __isascii and isupper must both return nonzero". winx_tolower has no such limitation.
Note
Converts ASCII characters only (as well as _tolower function included in ntdll library).
Definition at line 81 of file string.c.
wchar_t winx_towupper (wchar_t c)
Reliable towupper analog.
This routine doesn't depend on the current locale, it converts all the characters according to the Unicode standard.
Definition at line 93 of file string.c.
wchar_t winx_towlower (wchar_t c)
Reliable towlower analog.
This routine doesn't depend on the current locale, it converts all the characters according to the Unicode standard.
Definition at line 105 of file string.c.
wchar_t* winx_wcsupr (wchar_t * s)
Reliable _wcsupr analog.
This routine doesn't depend on the current locale, it converts all the characters according to the Unicode standard.
Definition at line 117 of file string.c.
wchar_t* winx_wcslwr (wchar_t * s)
Reliable _wcslwr analog.
This routine doesn't depend on the current locale, it converts all the characters according to the Unicode standard.
Definition at line 135 of file string.c.
int winx_wcsicmp (const wchar_t * s1, const wchar_t * s2)
Case insensitive version of wcscmp.
This routine doesn't depend on the current locale, it converts all the characters according to the Unicode standard.
Definition at line 187 of file string.c.
wchar_t* winx_wcsistr (const wchar_t * s1, const wchar_t * s2)
Case insensitive version of wcsstr.
This routine doesn't depend on the current locale, it converts all the characters according to the Unicode standard.
Definition at line 211 of file string.c.
Referenced by winx_defrag_fopen(), and winx_patfind().
char* winx_stristr (const char * s1, const char * s2)
Case insensitive version of strstr.
Note
Compares case insensitively ASCII characters only.
Definition at line 235 of file string.c.
Referenced by winx_hr_to_bytes().
int winx_wcsmatch (wchar_t * string, wchar_t * mask, int flags)
Compares a string with a mask.
Supports ? and * wildcards.
Parameters
[in] string the string to be compared with the mask.
[in] mask the mask to be compared with the string.
[in] flags the combination of WINX_PAT_xxx flags.
Returns
Nonzero value indicates that the string matches the mask.
Note
Optimized for speed.
Definition at line 353 of file string.c.
Referenced by winx_patcmp().
char* winx_vsprintf (const char * format, va_list arg)
Robust and flexible alternative to _vsnprintf.
Parameters
[in] format the format specification.
[in] arg pointer to list of arguments.
Returns
Pointer to the formatted string, NULL indicates failure. The string must be deallocated by winx_heap_free after its use.
Note
Optimized for speed, can allocate more memory than needed.
Definition at line 375 of file string.c.
References winx_heap_free().
Referenced by winx_dbg_print(), winx_dbg_print_ex(), winx_dbg_print_header(), winx_printf(), and winx_sprintf().
char* winx_sprintf (const char * format, ...)
Robust and flexible alternative to _snprintf.
Parameters
[in] format the format specification.
[in] ... the arguments.
Returns
Pointer to the formatted string, NULL indicates failure. The string must be deallocated by winx_heap_free after its use.
Note
Optimized for speed, can allocate more memory than needed.
Definition at line 418 of file string.c.
References winx_vsprintf().
Referenced by winx_dbg_print(), and winx_init_spin_lock().
int winx_patcomp (winx_patlist * patterns, wchar_t * string, wchar_t * delim, int flags)
Compiles string of patterns to internal representation.
Parameters
[out] patterns pointer to storage for a single winx_patlist structure.
[in] string the string of patterns.
[in] delim the list of delimiters to be used to split string to individual patterns.
[in] flags combination of WINX_PAT_xxx flags.
Returns
Zero for success, negative value otherwise.
Definition at line 445 of file string.c.
References winx_heap_free(), and winx_wcsdup().
int winx_patfind (wchar_t * string, winx_patlist * patterns)
Searches for patterns in a string.
Parameters
[in] string the string to search in.
[in] patterns the list of patterns to be searched for.
Returns
Nonzero value indicates that at least one pattern has been found.
Definition at line 524 of file string.c.
References winx_wcsistr().
int winx_patcmp (wchar_t * string, winx_patlist * patterns)
Compares a string with patterns.
Supports ? and * wildcards.
Parameters
[in] string the string to compare patterns with.
[in] patterns the list of patterns to be compared with the string.
Returns
Nonzero value indicates that at least one pattern matches the string.
Definition at line 553 of file string.c.
References winx_wcsmatch().
void winx_patfree (winx_patlist * patterns)
Frees resources allocated by winx_patcomp.
Parameters
[in] patterns the list of patterns.
Definition at line 572 of file string.c.
References winx_heap_free().
int winx_bytes_to_hr (ULONGLONG bytes, int digits, char * buffer, int length)
Converts number of bytes to a human readable string.
Parameters
[in] bytes number of bytes.
[in] digits number of digits after a dot.
[out] buffer pointer to string receiving converted number of bytes.
[in] length the length of the buffer, in characters.
Returns
A number of characters stored, not counting the terminating null character. If the number of characters required to store the data exceeds length, then length characters are stored in buffer and a negative value is returned.
Todo:
Investigate how many digits can be successfully calculated.
Definition at line 608 of file string.c.
ULONGLONG winx_hr_to_bytes (char * string)
Converts human readable string to number of bytes.
Supported suffixes: B, KB, MB, GB, TB, PB, EB, ZB, YB.
Parameters
[in] string string to be converted.
Returns
Number of bytes.
Note
Accepted values are below 16.0 Eb, all values above will be converted improperly.
Definition at line 653 of file string.c.
References winx_stristr().
void winx_to_utf8 (char * dst, int size, wchar_t * src)
Converts a string to UTF-8 encoding.
Parameters
[out] dst the destination buffer.
[in] size size of the destination buffer.
[in] src the source string.
Note
Each converted character needs maximum three bytes to be stored. So destination buffer should be at least (1.5 * src_bytes) long.
Definition at line 699 of file string.c.
Referenced by winx_dbg_print().