zenwinx: Time
Time
Functions
ULONGLONG winx_str2time (char *string)
Converts a formatted string to the time value in seconds.
int winx_time2str (ULONGLONG time, char *buffer, int size)
Converts a time value in seconds to the formatted string.
ULONGLONG winx_xtime (void)
Returns time interval since some abstract unique event in the past.
int winx_get_system_time (winx_time *t)
Retrieves the current system time (UTC) in a human understandable format.
int winx_get_local_time (winx_time *t)
Retrieves the current local time in a human understandable format.
Variables
int xtime_failed = 0
Internal variable used to log winx_xtime failure once.
Detailed Description
Function Documentation
ULONGLONG winx_str2time (char * string)
Converts a formatted string to the time value in seconds.
Parameters
[in] string the formatted string to be converted. Format example: 3y 12d 4h 8m 37s.
Returns
Time interval in seconds.
Definition at line 35 of file time.c.
References winx_toupper().
int winx_time2str (ULONGLONG time, char * buffer, int size)
Converts a time value in seconds to the formatted string.
Parameters
[in] time the time interval, in seconds.
[out] buffer the storage for the resulting string.
[in] size the length of the buffer, in characters.
Returns
The number of characters stored.
Note
The time interval should not exceed 140 years (0xFFFFFFFF seconds), otherwise it will be truncated.
Definition at line 92 of file time.c.
ULONGLONG winx_xtime (void)
Returns time interval since some abstract unique event in the past.
Returns
Time, in milliseconds. Zero indicates failure.
Note
Useful for performance measures.
Has no physical meaning.
Definition at line 134 of file time.c.
References xtime_failed.
Referenced by kb_read(), and winx_scan_disk().
int winx_get_system_time (winx_time * t)
Retrieves the current system time (UTC) in a human understandable format.
Parameters
[out] t pointer to structure receiving the current system time.
Returns
Zero for success, negative value otherwise.
Definition at line 173 of file time.c.
int winx_get_local_time (winx_time * t)
Retrieves the current local time in a human understandable format.
Parameters
[out] t pointer to structure receiving the current local time.
Returns
Zero for success, negative value otherwise.
Definition at line 207 of file time.c.
Variable Documentation
int xtime_failed = 0
Internal variable used to log winx_xtime failure once.
Definition at line 123 of file time.c.
Referenced by winx_xtime().