zenwinx: Disks
Disks
Functions
int winx_get_drive_type (char letter)
Win32 GetDriveType() native equivalent.
WINX_FILE * winx_vopen (char volume_letter)
Opens the volume for read access.
int winx_get_volume_information (char volume_letter, winx_volume_information *v)
Retrieves detailed information about disk volume.
int winx_vflush (char volume_letter)
fflush equivalent for entire volume.
winx_volume_region * winx_get_free_volume_regions (char volume_letter, int flags, volume_region_callback cb, void *user_defined_data)
Retrieves list of free regions on the volume.
winx_volume_region * winx_add_volume_region (winx_volume_region *rlist, ULONGLONG lcn, ULONGLONG length)
Adds a range of clusters to the list of regions.
winx_volume_region * winx_sub_volume_region (winx_volume_region *rlist, ULONGLONG lcn, ULONGLONG length)
Subtracts a range of clusters from the list of regions.
void winx_release_free_volume_regions (winx_volume_region *rlist)
Frees memory allocated by winx_get_free_volume_regions.
Detailed Description
Function Documentation
int winx_get_drive_type (char letter)
Win32 GetDriveType() native equivalent.
Parameters
[in] letter the volume letter
Returns
A drive type, negative value indicates failure.
Definition at line 68 of file volume.c.
References winx_heap_free(), winx_query_symbolic_link(), and winx_toupper().
WINX_FILE* winx_vopen (char volume_letter)
Opens the volume for read access.
Parameters
[in] volume_letter the volume letter.
Returns
File descriptor, NULL indicates failure.
Definition at line 365 of file volume.c.
References winx_fopen(), and winx_toupper().
Referenced by winx_get_free_volume_regions().
int winx_get_volume_information (char volume_letter, winx_volume_information * v)
Retrieves detailed information about disk volume.
Parameters
[in] volume_letter the volume letter.
[in,out] v pointer to structure receiving the volume information.
Returns
Zero for success, negative value otherwise.
Definition at line 622 of file volume.c.
References winx_toupper().
Referenced by winx_create_path(), and winx_scan_disk().
winx_volume_region* winx_get_free_volume_regions (char volume_letter, int flags, volume_region_callback cb, void * user_defined_data)
Retrieves list of free regions on the volume.
Parameters
[in] volume_letter the volume letter.
[in] flags combination of WINX_GVR_xxx flags.
[in] cb address of procedure to be called each time when the free region is found on the volume. If callback procedure returns nonzero value, the scan terminates immediately.
[in] user_defined_data pointer to data passed to the registered callback.
Returns
List of free regions, NULL indicates that either disk is full (unlikely) or some error occured.
Note
It is possible to scan disk partially by requesting the scan termination through the callback procedure.
Callback procedure should complete as quickly as possible to avoid slowdown of the scan.
Definition at line 714 of file volume.c.
References winx_fclose(), winx_heap_free(), winx_list_destroy(), winx_list_insert_item(), winx_toupper(), and winx_vopen().
winx_volume_region* winx_add_volume_region (winx_volume_region * rlist, ULONGLONG lcn, ULONGLONG length)
Adds a range of clusters to the list of regions.
Parameters
[in,out] rlist the list of volume regions.
[in] lcn the logical cluster number of the region to be added.
[in] length the size of the region to be added, in clusters.
Returns
Pointer to updated list of regions.
Note
For performance reason this routine doesn't insert regions of zero length.
Definition at line 850 of file volume.c.
References winx_list_insert_item(), and winx_list_remove_item().
Referenced by winx_sub_volume_region().
winx_volume_region* winx_sub_volume_region (winx_volume_region * rlist, ULONGLONG lcn, ULONGLONG length)
Subtracts a range of clusters from the list of regions.
Parameters
[in,out] rlist the list of volume regions.
[in] lcn the logical cluster number of the region to be subtracted.
[in] length the size of the region to be subtracted, in clusters.
Returns
Pointer to updated list of regions.
Definition at line 910 of file volume.c.
References winx_add_volume_region(), and winx_list_remove_item().