zenwinx: Miscellaneous
Miscellaneous
Functions
void winx_sleep (int msec)
Suspends the execution of the current thread.
int winx_get_os_version (void)
Returns the version of Windows.
int winx_get_windows_directory (char *buffer, int length)
Retrieves the path of the Windows directory.
int winx_query_symbolic_link (short *name, short *buffer, int length)
Queries a symbolic link.
int winx_set_system_error_mode (unsigned int mode)
Sets a system error mode.
int winx_load_driver (short *driver_name)
Loads a driver.
int winx_unload_driver (short *driver_name)
Unloads a driver.
short * winx_get_windows_boot_options (void)
Retrieves the Windows boot options.
int winx_windows_in_safe_mode (void)
Determines whether Windows is in Safe Mode or not.
void MarkWindowsBootAsSuccessful (void)
Marks Windows boot as successful.
Detailed Description
Function Documentation
void winx_sleep (int msec)
Suspends the execution of the current thread.
Parameters
[in] msec the time interval, in milliseconds. If an INFINITE constant is passed, the time-out interval never elapses.
Definition at line 35 of file misc.c.
Referenced by kb_close(), kb_read(), MarkWindowsBootAsSuccessful(), and winx_kb_init().
int winx_get_os_version (void)
Returns the version of Windows.
Returns
major_version_number * 10 + minor_version_number.
Note
Works fine on NT 4.0 and later systems. Otherwise always returns 40.
Useless on Windows 9x. Though, the complete zenwinx library is useless there since there are many required calls missing in ntdll library on windows 9x.
Example:
if(winx_get_os_version() >= WINDOWS_XP){
    // we are running on XP or later system
}
Definition at line 65 of file misc.c.
References winx_get_proc_address().
Referenced by winx_defrag_fopen().
int winx_get_windows_directory (char * buffer, int length)
Retrieves the path of the Windows directory.
Parameters
[out] buffer pointer to the buffer receiving the null-terminated path.
[in] length the length of the buffer, in characters.
Returns
Zero for success, negative value otherwise.
Note
This function retrieves a native path, like this \??\C:\WINDOWS
Definition at line 89 of file misc.c.
References winx_query_env_variable().
Referenced by MarkWindowsBootAsSuccessful().
int winx_query_symbolic_link (short * name, short * buffer, int length)
Queries a symbolic link.
Parameters
[in] name the name of symbolic link.
[out] buffer pointer to the buffer receiving the null-terminated target.
[in] length of the buffer, in characters.
Returns
Zero for success, negative value otherwise.
Example:
winx_query_symbolic_link(L"\\??\\C:",buffer,BUFFER_LENGTH);
// now the buffer may contain \Device\HarddiskVolume1 or something like that
Definition at line 114 of file misc.c.
Referenced by winx_get_drive_type().
int winx_set_system_error_mode (unsigned int mode)
Sets a system error mode.
Parameters
[in] mode the process error mode.
Returns
Zero for success, negative value otherwise.
Note
Mode constants aren't the same as in Win32 SetErrorMode() call.
Use INTERNAL_SEM_FAILCRITICALERRORS constant to disable the critical-error-handler message box. After that you can for example try to read a missing floppy disk without any popup windows displaying error messages.
winx_set_system_error_mode(1) call is equal to SetErrorMode(0).
Other mode constants can be found in ReactOS sources, but they need to be tested carefully because they were never officially documented.
Example:
winx_set_system_error_mode(INTERNAL_SEM_FAILCRITICALERRORS);
Definition at line 164 of file misc.c.
int winx_load_driver (short * driver_name)
Loads a driver.
Parameters
[in] driver_name the name of the driver, exactly as written in system registry.
Returns
Zero for success, negative value otherwise.
Note
When the driver is already loaded this function completes successfully.
Definition at line 188 of file misc.c.
int winx_unload_driver (short * driver_name)
Unloads a driver.
Parameters
[in] driver_name the name of the driver, exactly as written in system registry.
Returns
Zero for success, negative value otherwise.
Definition at line 214 of file misc.c.
short* winx_get_windows_boot_options (void)
Retrieves the Windows boot options.
Returns
Pointer to Unicode string containing all Windows boot options. NULL indicates failure.
Note
After a use of returned string it should be freed by winx_heap_free() call.
Definition at line 241 of file misc.c.
References winx_heap_free(), and winx_printf().
Referenced by winx_windows_in_safe_mode().
int winx_windows_in_safe_mode (void)
Determines whether Windows is in Safe Mode or not.
Returns
Positive value indicates the presence of the Safe Mode. Zero value indicates a normal boot. Negative value indicates indeterminism caused by impossibility of an appropriate check.
Definition at line 330 of file misc.c.
References winx_get_windows_boot_options(), and winx_heap_free().
void MarkWindowsBootAsSuccessful (void)
Marks Windows boot as successful.
Note
Based on http://www.osronline.com/showthread.cfm?link=185567
Is used internally by winx_shutdown and winx_reboot.
Definition at line 353 of file misc.c.
References winx_fclose(), winx_fopen(), winx_fwrite(), winx_get_windows_directory(), winx_printf(), and winx_sleep().
Referenced by winx_reboot(), and winx_shutdown().