zenwinx: Startup and shutdown
Startup and shutdown
Functions
void kb_close (void)
Closes all opened keyboards.
int winx_create_global_heap (void)
Creates global memory heap.
void winx_destroy_global_heap (void)
Destroys global memory heap.
int winx_dbg_init (void)
Initializes the debugging facility.
void winx_dbg_close (void)
Deinitializes the debugging facility.
void MarkWindowsBootAsSuccessful (void)
Marks Windows boot as successful.
char * winx_get_error_description (unsigned long status)
Retrieves a human readable explanation of the NT status code.
void winx_init_case_tables (void)
Initializes tables for the character case conversion.
int winx_init_library (void *peb)
Initializes zenwinx library.
int winx_init_failed (void)
Defines whether zenwinx library has been initialized successfully or not.
void winx_unload_library (void)
Frees resources allocated by zenwinx library.
void winx_exit (int exit_code)
Terminates the calling native process.
void winx_reboot (void)
Reboots the computer.
void winx_shutdown (void)
Shuts down the computer.
Variables
int initialization_failed = 1
Internal variable indicating whether library initialization failed or not. Intended to be checked by winx_init_failed routine.
Detailed Description
Function Documentation
void kb_close (void)
Closes all opened keyboards.
Definition at line 254 of file keyboard.c.
References winx_destroy_event(), winx_printf(), and winx_sleep().
Referenced by winx_exit(), winx_reboot(), and winx_shutdown().
int winx_create_global_heap (void)
Creates global memory heap.
Returns
Zero for success, negative value otherwise.
Definition at line 95 of file mem.c.
References winx_print().
Referenced by winx_init_library().
void winx_destroy_global_heap (void)
Destroys global memory heap.
Definition at line 114 of file mem.c.
Referenced by winx_unload_library().
int winx_dbg_init (void)
Initializes the debugging facility.
Returns
Zero for success, negative value otherwise.
Definition at line 65 of file dbg.c.
References winx_init_spin_lock().
Referenced by winx_init_library().
void winx_dbg_close (void)
Deinitializes the debugging facility.
Definition at line 79 of file dbg.c.
References winx_destroy_spin_lock().
Referenced by winx_unload_library().
void MarkWindowsBootAsSuccessful (void)
Marks Windows boot as successful.
Note
Based on http://www.osronline.com/showthread.cfm?link=185567
Is used internally by winx_shutdown and winx_reboot.
Definition at line 353 of file misc.c.
References winx_fclose(), winx_fopen(), winx_fwrite(), winx_get_windows_directory(), winx_printf(), and winx_sleep().
Referenced by winx_reboot(), and winx_shutdown().
char* winx_get_error_description (unsigned long status)
Retrieves a human readable explanation of the NT status code.
Parameters
[in] status the NT status code.
Returns
A pointer to string containing the status explanation.
Note
This function returns explanations only for well known codes. Otherwise it returns an empty string.
Example:
printf("%s\n",winx_get_error_description(STATUS_ACCESS_VIOLATION));
// prints "access violation"
Definition at line 525 of file dbg.c.
Referenced by kb_read().
void winx_init_case_tables (void)
Initializes tables for the character case conversion.
Definition at line 50 of file string.c.
Referenced by winx_init_library().
int winx_init_library (void * peb)
Initializes zenwinx library.
If the library is linked statically this routine needs to be called explicitly before any use of other routines (except a few ones like winx_print).
Parameters
[in] peb pointer to the Process Environment Block. May be NULL.
Returns
Zero for success, negative value otherwise.
Example 1 - a native application:
void __stdcall NtProcessStartup(PPEB Peb)
{
    winx_init_library(Peb);
    winx_kb_init();
    // do something
    winx_printf("Hello!");
    winx_sleep(1000);
    winx_exit(0);
}
Example 2 - a command line tool (zenwinx is linked statically):
int main(void)
{
    winx_init_library(NULL);
    // do something
    printf("Hello!");
    winx_sleep(1000);
    winx_unload_library();
    return 0;
}
Example 3 - a command line tool (zenwinx is linked dynamically):
int main(void)
{
    // do something
    printf("Hello!");
    winx_sleep(1000);
    return 0;
}
Definition at line 108 of file zenwinx.c.
References initialization_failed, winx_create_global_heap(), winx_dbg_init(), and winx_init_case_tables().
int winx_init_failed (void)
Defines whether zenwinx library has been initialized successfully or not.
Useful for non-native applications making no direct call to winx_init_library.
Returns
Boolean value.
Definition at line 138 of file zenwinx.c.
References initialization_failed.
void winx_unload_library (void)
Frees resources allocated by zenwinx library.
If the library is linked statically to the non-native application this routine needs to be called explicitly.
Definition at line 149 of file zenwinx.c.
References winx_dbg_close(), and winx_destroy_global_heap().
Referenced by winx_exit().
void winx_exit (int exit_code)
Terminates the calling native process.
This routine releases all resources used by zenwinx library before the process termination.
Parameters
[in] exit_code the exit status.
Definition at line 182 of file zenwinx.c.
References kb_close(), winx_flush_dbg_log(), and winx_unload_library().
void winx_reboot (void)
Reboots the computer.
Note
If SE_SHUTDOWN privilege adjusting fails then the computer will not be rebooted and the program will continue the execution after this call.
Definition at line 201 of file zenwinx.c.
References kb_close(), MarkWindowsBootAsSuccessful(), winx_enable_privilege(), and winx_flush_dbg_log().
void winx_shutdown (void)
Shuts down the computer.
Note
If SE_SHUTDOWN privilege adjusting fails then the computer will not be shut down and the program will continue the execution after this call.
Definition at line 221 of file zenwinx.c.
References kb_close(), MarkWindowsBootAsSuccessful(), winx_enable_privilege(), and winx_flush_dbg_log().
Variable Documentation
int initialization_failed = 1
Internal variable indicating whether library initialization failed or not. Intended to be checked by winx_init_failed routine.
Definition at line 45 of file zenwinx.c.
Referenced by winx_init_failed(), and winx_init_library().