zenwinx: Locks
Locks
Functions
winx_spin_lock * winx_init_spin_lock (char *name)
Initializes a spin lock.
int winx_acquire_spin_lock (winx_spin_lock *sl, int msec)
Acquires a spin lock.
int winx_release_spin_lock (winx_spin_lock *sl)
Releases a spin lock.
void winx_destroy_spin_lock (winx_spin_lock *sl)
Destroys a spin lock.
Detailed Description
Function Documentation
winx_spin_lock* winx_init_spin_lock (char * name)
Initializes a spin lock.
Parameters
[in] name the name of the spin lock.
Returns
Pointer to intialized spin lock. NULL indicates failure.
Definition at line 43 of file lock.c.
References winx_create_event(), winx_destroy_event(), winx_heap_free(), winx_release_spin_lock(), and winx_sprintf().
Referenced by winx_dbg_init().
int winx_acquire_spin_lock (winx_spin_lock * sl, int msec)
Acquires a spin lock.
Parameters
[in] sl pointer to the spin lock.
[in] msec the timeout interval. If INFINITE constant is passed, the interval never elapses.
Returns
Zero for success, negative value otherwise.
Definition at line 109 of file lock.c.
Referenced by winx_enable_dbg_log().
int winx_release_spin_lock (winx_spin_lock * sl)
Releases a spin lock.
Returns
Zero for success, negative value otherwise.
Definition at line 136 of file lock.c.
Referenced by winx_enable_dbg_log(), and winx_init_spin_lock().