zenwinx: Memory
Memory
Functions
void * winx_virtual_alloc (SIZE_T size)
Allocates a block of virtual memory.
void winx_virtual_free (void *addr, SIZE_T size)
Releases a block of virtual memory.
void * winx_heap_alloc_ex (SIZE_T size, SIZE_T flags)
Allocates a block of memory from the global growable heap.
void winx_heap_free (void *addr)
Frees memory allocated by winx_heap_alloc_ex.
int winx_create_global_heap (void)
Creates global memory heap.
void winx_destroy_global_heap (void)
Destroys global memory heap.
Detailed Description
Function Documentation
void* winx_virtual_alloc (SIZE_T size)
Allocates a block of virtual memory.
Parameters
[in] size the size of the block to be allocated, in bytes. Note that the allocated block may be bigger than the requested size.
Returns
A pointer to the allocated block. NULL indicates failure.
Note
Allocated memory is automatically initialized to zero.
Memory protection for the allocated pages is PAGE_READWRITE.
Definition at line 40 of file mem.c.
void winx_virtual_free (void * addr, SIZE_T size)
Releases a block of virtual memory.
Parameters
[in] addr address of the memory block.
[in] size the size of the block to be released, in bytes.
Definition at line 55 of file mem.c.
void* winx_heap_alloc_ex (SIZE_T size, SIZE_T flags)
Allocates a block of memory from the global growable heap.
Parameters
size the size of the block to be allocated, in bytes. Note that the allocated block may be bigger than the requested size.
flags HEAP_ZERO_MEMORY to initialize memory to zero, zero otherwise.
Returns
A pointer to the allocated block. NULL indicates failure.
Definition at line 67 of file mem.c.
void winx_heap_free (void * addr)
Frees memory allocated by winx_heap_alloc_ex.
Parameters
[in] addr address of the memory block.
Definition at line 81 of file mem.c.
Referenced by winx_dbg_print(), winx_dbg_print_ex(), winx_dbg_print_header(), winx_destroy_history(), winx_destroy_spin_lock(), winx_enable_dbg_log(), winx_fclose(), winx_ftw_dump_file(), winx_ftw_release(), winx_get_drive_type(), winx_get_file_contents(), winx_get_free_volume_regions(), winx_get_windows_boot_options(), winx_init_spin_lock(), winx_list_destroy(), winx_list_remove_item(), winx_patcomp(), winx_patfree(), winx_print_array_of_strings(), winx_printf(), winx_prompt_ex(), winx_register_boot_exec_command(), winx_release_file_contents(), winx_unregister_boot_exec_command(), winx_vsprintf(), and winx_windows_in_safe_mode().
int winx_create_global_heap (void)
Creates global memory heap.
Returns
Zero for success, negative value otherwise.
Definition at line 95 of file mem.c.
References winx_print().
Referenced by winx_init_library().
void winx_destroy_global_heap (void)
Destroys global memory heap.
Definition at line 114 of file mem.c.
Referenced by winx_unload_library().