gui: MainWindow
MainWindow
Functions
LRESULT CALLBACK MainWindowProc (HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam)
Main window procedure.
void ResizeMainWindow (int force)
Adjust positions of controls in accordance with main window dimensions.
int CreateMainWindow (int nShowCmd)
Creates main window.
void OpenWebPage (char *page, char *anchor)
Opens a page of the handbook, either from local storage or from the network.
void OpenTranslationWebPage (wchar_t *page, int islang)
Opens a page of the translation wiki.
void OpenLog (void)
Opens the log file.
DWORD WINAPI UpdateWebStatisticsThreadProc (LPVOID lpParameter)
Updates web statistics of the program use.
void start_web_statistics (void)
Starts web statistics request delivering.
void stop_web_statistics ()
Waits for web statistics request completion.
int WINAPI WinMain (HINSTANCE hInst, HINSTANCE hPrevInst, LPSTR lpCmdLine, int nShowCmd)
Entry point.
Detailed Description
Function Documentation
int CreateMainWindow (int nShowCmd)
Creates main window.
Returns
Zero for success, negative value otherwise.
Definition at line 421 of file main.c.
References ApplyLanguagePack(), BuildLanguageMenu(), CreateMainMenu(), CreateStatusBar(), CreateToolbar(), InitFont(), InitMap(), InitVolList(), ResizeMainWindow(), UpdateStatusBar(), and UpdateVolList().
Referenced by WinMain().
void OpenTranslationWebPage (wchar_t * page, int islang)
Opens a page of the translation wiki.
Parameters
[in] page name of the page
[in] islang 1 indicates a language page, 0 not
Definition at line 624 of file main.c.
Referenced by MainWindowProc().
DWORD WINAPI UpdateWebStatisticsThreadProc (LPVOID lpParameter)
Updates web statistics of the program use.
Definition at line 1225 of file main.c.
Referenced by start_web_statistics().