gui: ListOfVolumes
ListOfVolumes
Functions
LRESULT CALLBACK ListWndProc (HWND hWnd, UINT iMsg, WPARAM wParam, LPARAM lParam)
Custom window procedure for the list control.
volume_processing_job * get_first_selected_job (void)
Retrieves the first job selected in the list.
void InitVolList (void)
Initializes the list of volumes.
int ResizeVolList (int x, int y, int width, int height, int expand)
Resizes the list of volumes.
int GetMinVolListHeight (void)
Calculates a minimal height of the list.
int GetMaxVolListHeight (void)
Calculates a maximal height of the list.
void ReleaseVolList (void)
Frees resources allocated for the list of volumes.
void VolListNotifyHandler (LPARAM lParam)
Handles notifications from the list of volumes.
void SetVolumeDirtyStatus (int index, volume_info *v)
Marks a volume as dirty or as clean.
void UpdateVolList (void)
Updates the list of volumes.
void VolListGetColumnWidths (void)
Saves widths of the volume list columns.
int get_job_index (volume_processing_job *job)
Retrieves an index of the specified job as it is listed in the list of volumes.
void VolListUpdateStatusField (volume_processing_job *job)
Updates job processing status in the list.
void VolListUpdateFragmentationField (volume_processing_job *job)
Updates fragmentation percentage in the list.
void VolListRefreshItem (volume_processing_job *job)
Updates volume capacity fields in the list.
void SelectAllDrives (void)
Selects all drives in the list.
Detailed Description
Function Documentation
void VolListUpdateStatusField (volume_processing_job * job)
Updates job processing status in the list.
Decides themselves on which position in list the job locates.
Definition at line 634 of file vollist.c.
References get_job_index().
Referenced by update_status_of_all_jobs().
void VolListUpdateFragmentationField (volume_processing_job * job)
Updates fragmentation percentage in the list.
Decides themselves on which position in list the job locates.
Definition at line 648 of file vollist.c.
References get_job_index().