gui: Job
Job
Functions
void init_jobs (void)
Initializes structures belonging to all jobs.
volume_processing_job * get_job (char volume_letter)
Get job assigned to volume letter.
void update_status_of_all_jobs (void)
Updates status field of the list for all volumes.
DWORD WINAPI StartJobsThreadProc (LPVOID lpParameter)
start_selected_jobs thread routine.
void start_selected_jobs (udefrag_job_type job_type)
Runs sequentially all selected jobs.
void stop_all_jobs (void)
Stops all running jobs.
void release_jobs (void)
Frees resources allocated for all jobs.
void RepairSelectedVolumes (void)
Tries to repair all selected volumes.
Detailed Description
Function Documentation
DWORD WINAPI StartJobsThreadProc (LPVOID lpParameter)
start_selected_jobs thread routine.
Definition at line 284 of file job.c.
References get_job(), RemoveTaskbarIconOverlay(), and SetTaskbarIconOverlay().
Referenced by start_selected_jobs().