gui: ClusterMap
ClusterMap
Functions
LRESULT CALLBACK RectWndProc (HWND hWnd, UINT iMsg, WPARAM wParam, LPARAM lParam)
Custom cluster map window procedure.
void InitMap (void)
Initializes cluster map.
void ResizeMap (int x, int y, int width, int height)
Resizes cluster map.
void RedrawMap (volume_processing_job *job, int map_refill_required)
Redraws cluster map.
void ReleaseMap (void)
Frees all resources allocated for cluster map.
Detailed Description
Function Documentation
void ResizeMap (int x, int y, int width, int height)
Resizes cluster map.
Note
Not safe to be called from threads, post WM_RESIZE_MAP message to the map control instead.
Definition at line 131 of file map.c.
Referenced by RectWndProc(), and ResizeMainWindow().
void RedrawMap (volume_processing_job * job, int map_refill_required)
Redraws cluster map.
Note
Since v3.1.0 all screen color depths are supported.
Definition at line 273 of file map.c.
Referenced by PrefsChangesTrackingProc(), RectWndProc(), and VolListNotifyHandler().